version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - kanboard_data:/var/www/app/data
     - kanboard_plugins:/var/www/app/plugins
     - kanboard_ssl:/etc/nginx/ssl
    environment: 
      DATABASE_URL: postgres://postgres:postgres@db:5432/kanboard
      DEBUG: "true"
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanboard
    ports:
      - 5432:5432
    # command: "psql -U postgres -c \"CREATE DATABASE kanboard\""
    # entrypoint: "psql -U postgres -c \"CREATE DATABASE kanboard\""
    # command: bash -c "echo \"TERRY WAS HERE\""
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local
